apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: xxx
    server: xxx
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    namespace: xxx
    user: xxx.config
  name: xxx.config
current-context: xxx.config
kind: Config
preferences: {}
users:
- name: xxx.config
  user:
    token: xxx